### ISSUE TITLE
Still Alive?

### ISSUE THREAD

**Issue by vertyco** [Sebass13/aiorcon#4]
Been 3 years since the API was updated. Just wondering if there's a better alternative async rcon api out there or if there are plans of an update in the near future?

**Comment by 991jo** [comment]
I am currently not aware of other async rcon libraries. As far as I am aware there haven't been any changes to the RCON protocol (pls correct me if I am wrong) and currently the API is considered "complete". So there hasn't been the need for an update.

If you find bugs or are missing a feature, feel free to open an issue.

**Comment by 991jo** [comment]
I am closing this, because I thing this question is answered. Feel free to reopen it if you want to continue the discussion.
